/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OPERATIONS_H_RPCGEN
#define _OPERATIONS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operation_data {
	char *username;
	char *operation;
	char *datetime;
};
typedef struct operation_data operation_data;

#define OPERATIONS_PROG 0x20000001
#define OPERATIONS_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PRINT_OPERATION 1
extern  void * print_operation_1(operation_data *, CLIENT *);
extern  void * print_operation_1_svc(operation_data *, struct svc_req *);
extern int operations_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PRINT_OPERATION 1
extern  void * print_operation_1();
extern  void * print_operation_1_svc();
extern int operations_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operation_data (XDR *, operation_data*);

#else /* K&R C */
extern bool_t xdr_operation_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OPERATIONS_H_RPCGEN */
