/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "operations.h"

bool_t
xdr_operation_data (XDR *xdrs, operation_data *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->username, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->operation, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->datetime, ~0))
		 return FALSE;
	return TRUE;
}
