/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */


#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "utils.h"
#include "claves.h"

int
main (int argc, char *argv[])
{
    int result = init();
    printf("Result: %d\n", result);

    int key1 = 100;
    char *cadena1 = "hello";
    int N1 = 2;
    double vector1[2] = {1.1, 1.2};

    int key2 = 200;
    char *cadena2 = "byebye";
    int N2 = 3;
    double vector2[3] = {2.1, 2.2, 2.3};

    int key3 = 300;
    char *cadena3 = "gdaymate";
    int N3 = 4;
    double vector3[4] = {3.1, 3.2, 3.3, 3.4};

    // Set

    result = set_value(key1, cadena1, N1, vector1);
    printf("Result: %d\n", result);
    result = set_value(key1, cadena1, N1, vector1);
    printf("Result: %d\n", result);
    result = set_value(key2, cadena2, N2, vector2);
    printf("Result: %d\n", result);
    result = set_value(key3, cadena3, N3, vector3);
    printf("Result: %d\n", result);

    // Get
    
    char cadena_res[256];
    int N_res;
    double vector_res[32] ;

    result = get_value(key1, cadena_res, &N_res, vector_res);
    printf("Result: %d, %s, %d, ", result, cadena_res, N_res);
    print_double_array(vector_res, N_res);

    result = get_value(key2, cadena_res, &N_res, vector_res);
    printf("Result: %d, %s, %d, ", result, cadena_res, N_res);
    print_double_array(vector_res, N_res);

    result = get_value(key3, cadena_res, &N_res, vector_res);
    printf("Result: %d, %s, %d, ", result, cadena_res, N_res);
    print_double_array(vector_res, N_res);

    result = get_value(400, cadena_res, &N_res, vector_res);
    printf("Result: %d, %s, %d, ", result, cadena_res, N_res);
    print_double_array(vector_res, N_res);

    // Modify

    char *cadena4 = "Pablo Garcia";
    int N4 = 5;
    double vector4[5] = {4.1, 4.2, 4.3, 4.4, 4.5};

    char *cadena5 = "Pablo Garcia Rius";
    int N5 = 6;
    double vector5[6] = {5.1, 5.2, 5.3, 5.4, 5.5, 5.6};

    result = modify_value(key2, cadena4, N4, vector4);
    printf("Result: %d\n", result);

    result = modify_value(key3, cadena5, N5, vector5);
    printf("Result: %d\n", result);

    result = modify_value(400, cadena5, N5, vector5);
    printf("Result: %d\n", result);

    result = get_value(key2, cadena_res, &N_res, vector_res);
    printf("Result: %d, %s, %d, ", result, cadena_res, N_res);
    print_double_array(vector_res, N_res);

    result = get_value(key3, cadena_res, &N_res, vector_res);
    printf("Result: %d, %s, %d, ", result, cadena_res, N_res);
    print_double_array(vector_res, N_res);

    // Delete

    result = delete_key(key3);
    printf("Result: %d\n", result);

    // Exists

    result = exist(key2);
    printf("Result: %d\n", result);

    result = exist(key3);
    printf("Result: %d\n", result);

    exit (0); 
}
